version: "3.8"

services:
  mbart-translate-api:
    build:
      context: .
      dockerfile: Dockerfile
    image: tys/mbart-translate-api:latest
    container_name: mbart-translate-api
    ports:
      - "23129:23129"
    environment:
      - MODEL_PATH=/data/models
    volumes:
      - ./:/app
      - /YOUR/LOCAL/PATH:/data/models
