version: "3.8"

services:
  mbart-translate-api:
    build:
      context: .
      dockerfile: Dockerfile
    image: tys/mbart-translate-api:latest
    container_name: mbart-translate-api
    restart: always
    ports:
      - "23129:23129"
    env_file:
      - .env.example
    environment:
      - MODEL_PATH=/data/models
      - DEVICE=cuda
    volumes:
      - $PWD:/app
      - /YOUR/LOCAL/PATH:/data/models
