version: "3.8"

services:
  mbart-translate-api:
    build:
      context: .
      dockerfile: Dockerfile
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    image: tys/mbart-translate-api:latest
    container_name: mbart-translate-api
    ports:
      - "23129:23129"
    environment:
      - MODEL_PATH=/data/models
    volumes:
      - /YOUR/LOCAL/PATH:/data/models
